# Generated by Django 2.2.2 on 2019-12-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articles',
            table='article',
        ),
    ]
