# Generated by Django 2.2.2 on 2019-12-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0002_auto_20191207_1554'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articles',
            table='articles',
        ),
    ]
