# Generated by Django 2.2.2 on 2019-12-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0004_miniurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiniURL',
        ),
    ]
