# Generated by Django 2.2.2 on 2020-01-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0005_delete_miniurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo1_article',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='prix_article',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
