# Generated by Django 2.2.2 on 2020-01-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0006_auto_20200112_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo1_article',
            field=models.ImageField(null=True, upload_to='ebsite/media'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='photo2_article',
            field=models.URLField(blank=True, null=True),
        ),
    ]
