# Generated by Django 2.2.2 on 2020-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0007_auto_20200119_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='photo1_article',
            field=models.ImageField(default='media/comingsoon.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='photo2_article',
            field=models.ImageField(default='media/comingsoon.png', upload_to='media/'),
        ),
    ]
