# Generated by Django 2.2.2 on 2020-03-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0008_auto_20200119_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
