# Generated by Django 2.2.2 on 2020-04-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0009_articles_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_client', models.CharField(max_length=200)),
                ('nom_client', models.CharField(max_length=200)),
                ('email_client', models.EmailField(max_length=254, unique=True)),
                ('date_crea_client', models.DateField()),
                ('genre_client', models.NullBooleanField()),
                ('password_hash_client', models.CharField(max_length=64)),
                ('password_salt_client', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_contact', models.CharField(max_length=200)),
                ('nom_contact', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('rue', models.CharField(max_length=200)),
                ('codepostal', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('adress_default_billing', models.BooleanField(default=False)),
                ('adress_default_shipping', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsite.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsite.Client')),
                ('shipping_adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsite.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsite.Articles')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsite.Order')),
            ],
        ),
    ]
