# Generated by Django 2.2.2 on 2020-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0010_client_contact_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
            preserve_default=False,
        ),
    ]
