# Generated by Django 2.2.2 on 2020-04-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0011_orderdetail_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsite.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebsite.Articles')),
            ],
            options={
                'verbose_name': "Ligne d'un panier client",
                'verbose_name_plural': "Lignes d'un panier client",
            },
        ),
    ]
