# Generated by Django 2.2.2 on 2020-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0013_auto_20200409_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='mur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('pseudo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'message',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='default_invoicing_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='default_shipping_address',
        ),
    ]
