# Generated by Django 2.2.2 on 2020-06-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebsite', '0014_auto_20200508_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mur',
            options={},
        ),
    ]
